name: transit-dashboard-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.2
  - numpy=1.26.4
  - pyarrow=17.0.0
  - streamlit=1.38.0
  - plotly=5.24.1
  - folium=0.16.0
  - pip
  - pip:
      - streamlit-folium==0.21.1
